#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EveryBag.Droid.Resource", IsApplication=true)]

namespace EveryBag.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::EveryBag.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::EveryBag.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::EveryBag.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::EveryBag.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::EveryBag.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::EveryBag.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::EveryBag.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::EveryBag.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::EveryBag.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::EveryBag.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::EveryBag.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::EveryBag.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::EveryBag.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::EveryBag.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::EveryBag.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::EveryBag.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::EveryBag.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::EveryBag.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::EveryBag.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::EveryBag.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::EveryBag.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_cart_layout = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cursor_color = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dotted_line = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_text_circle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int edit_text_style = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int grey_circle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_add_black_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_add_black_dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_checkout_black_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_drawer = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_settings_black_24dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int image_layout = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logo_with_shadow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int relative_layout = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int relative_layout_cart_total = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int relative_layout_item = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int relativelayout_item_detail = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int settingsmenu = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040022
			public const int ActionBarName = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int AddCartButton = 2130968611;
			
			// aapt resource value: 0x7f040002
			public const int BackButton = 2130968578;
			
			// aapt resource value: 0x7f04000c
			public const int CartDetailImage = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int CartDetailPrice = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int CartDetailTitle = 2130968589;
			
			// aapt resource value: 0x7f040005
			public const int CartImage11 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int CartImage22 = 2130968582;
			
			// aapt resource value: 0x7f040025
			public const int CartItem = 2130968613;
			
			// aapt resource value: 0x7f040007
			public const int CartItemNameRelativeLayout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int CartItemNameText = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int CartItemUpdateText = 2130968585;
			
			// aapt resource value: 0x7f04001d
			public const int CartItemsList = 2130968605;
			
			// aapt resource value: 0x7f04000b
			public const int CartItemsPriceText = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int CartItemsTotalText = 2130968586;
			
			// aapt resource value: 0x7f040015
			public const int CartShippingPlaceId = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int CartShippingText = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int CartSubTotalId = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int CartSubTotalText = 2130968594;
			
			// aapt resource value: 0x7f040003
			public const int CartTitleBarName = 2130968579;
			
			// aapt resource value: 0x7f04001f
			public const int CheckoutButton = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int CustomActionBar = 2130968608;
			
			// aapt resource value: 0x7f040019
			public const int DottedLine = 2130968601;
			
			// aapt resource value: 0x7f040027
			public const int EmailText = 2130968615;
			
			// aapt resource value: 0x7f040026
			public const int EveryBagLogo = 2130968614;
			
			// aapt resource value: 0x7f04002b
			public const int ForgotPasswordButton = 2130968619;
			
			// aapt resource value: 0x7f04001a
			public const int InclusiveTaxesText = 2130968602;
			
			// aapt resource value: 0x7f040011
			public const int InnerCartTotalLayout = 2130968593;
			
			// aapt resource value: 0x7f04002c
			public const int LoginInButton = 2130968620;
			
			// aapt resource value: 0x7f040021
			public const int MenuDrawer = 2130968609;
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f04002a
			public const int Password = 2130968618;
			
			// aapt resource value: 0x7f040029
			public const int PasswordText = 2130968617;
			
			// aapt resource value: 0x7f04001e
			public const int PrintButton = 2130968606;
			
			// aapt resource value: 0x7f040024
			public const int ProgressBar = 2130968612;
			
			// aapt resource value: 0x7f040018
			public const int PromoDiscountId = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int PromoDiscountText = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int ShippingCostId = 2130968598;
			
			// aapt resource value: 0x7f04000f
			public const int SoldByName = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int SoldByTitle = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int TitleBarSettings = 2130968580;
			
			// aapt resource value: 0x7f04001c
			public const int TotalAmountId = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int TotalText = 2130968603;
			
			// aapt resource value: 0x7f040028
			public const int Username = 2130968616;
			
			// aapt resource value: 0x7f04002d
			public const int menu1 = 2130968621;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int cart_detail_actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int cart_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int cart_item_detail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int cart_total = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CartItemDetailsView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CartItemsView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoginPageView = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050009
			public const int LoginText = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int bagsText = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int checkout = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int emailText = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int forgotPasswordText = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int passwordText = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int promoDiscountText = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int shippingText = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int subtotal = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int totalText = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
